apiVersion: v1
kind: Pod
metadata:
  name: initpod
  namespace: default  
spec:
  containers:
  - name: afterinit
    image: busybox:1.28
    command: ['sh', '-c', 'echo its running! && sleep 3600']

  initContainers:
  - name: init-service
    image: busybox:1.28
    command: ['sh', '-c', 'until nslookup myservice; do echo waiting for myservice; sleep 2; done;']
    
# kubectl expose deployment newnginx --port=80 --name=myservice

