apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  namespace: default 
  labels: 
    app: busybox
spec: 
  containers: 
  - name: busy
    image: busybox
    command:
      - sleep
      - "3600"
# kubectl create -f busybox.yaml
# kuebctl explain pod.spec  inforamtion about pod spec 